services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gui_spector
      MYSQL_USER: guiuser  
      MYSQL_PASSWORD: guipass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: python -m celery -A config worker -l info
    #env_file:
      #- .env
    volumes:
      - ./webapp:/app/webapp
      - ./gui_spector:/app/gui_spector
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - mysql
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_HOST=mysql
      - DATABASE_NAME=gui_spector
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: agent
    environment:
      - NUM_DISPLAYS=5
    ports:
      - "5900:5900"
      - "5901:5901"
      - "5902:5902"
      - "5903:5903"
      - "5904:5904"
    restart: unless-stopped

volumes:
  mysql_data: 