# Generated by Django 5.2.6 on 2025-09-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_url', models.URLField()),
                ('state', models.CharField(choices=[('success', 'Success'), ('processing', 'Processing'), ('pending', 'Pending'), ('failed', 'Failed'), ('started', 'Started')], default='success', max_length=16)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='setups/screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('met', 'Met'), ('unmet', 'Unmet')], default='unknown', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='setups.setup')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='setup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='setups', to='setups.tag'),
        ),
    ]
