# Generated by Django 5.2.6 on 2025-09-20 20:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='acceptance_criteria_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='requirement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='framework_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='metadata_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='tags_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='requirement',
            name='title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
