# Generated by Django 5.2.6 on 2025-09-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_requirement_acceptance_criteria_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='text',
        ),
    ]
