# Generated by Django 5.2.6 on 2025-09-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0003_remove_requirement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('met', 'Met'), ('partially_met', 'Partially met'), ('unmet', 'Unmet')], default='unprocessed', max_length=16),
        ),
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('met', 'Met'), ('not_met', 'Not met'), ('partially_met', 'Partially met')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('elapsed_s', models.FloatField()),
                ('start_url', models.URLField()),
                ('current_url', models.URLField(blank=True, null=True)),
                ('steps_taken', models.IntegerField(default=0)),
                ('run_dir', models.CharField(max_length=1024)),
                ('model_decision_json', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('usage_total_json', models.JSONField(blank=True, null=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='setups.requirement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('elapsed_s', models.FloatField()),
                ('model_response_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reasoning_summary', models.TextField(blank=True, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('usage_json', models.JSONField(blank=True, null=True)),
                ('action_type', models.CharField(blank=True, max_length=64, null=True)),
                ('action_params_json', models.JSONField(blank=True, null=True)),
                ('action_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_status', models.CharField(blank=True, max_length=64, null=True)),
                ('action_safety_checks_json', models.JSONField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='setups.verificationrun')),
            ],
            options={
                'ordering': ['turn_index'],
            },
        ),
    ]
