# Generated by Django 5.2.6 on 2025-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0004_alter_requirement_status_verificationrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrun',
            name='display_str',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrun',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('met', 'Met'), ('not_met', 'Not met'), ('partially_met', 'Partially met')], max_length=16),
        ),
    ]
