# Generated by Django 5.2.6 on 2025-09-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0005_verificationrun_display_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrun',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('met', 'Met'), ('not_met', 'Not met'), ('partially_met', 'Partially met'), ('error', 'Error')], max_length=16),
        ),
    ]
