# Generated by Django 5.2.6 on 2025-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0006_alter_verificationrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrun',
            name='last_screenshot',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('met', 'Met'), ('partially_met', 'Partially met'), ('unmet', 'Unmet'), ('error', 'Error'), ('not_met', 'Not met')], default='unprocessed', max_length=16),
        ),
    ]
