# Generated by Django 5.2.6 on 2025-09-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0007_verificationrun_last_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='state',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing')], default='ready', max_length=16),
        ),
    ]
