# Generated by Django 5.2.6 on 2025-09-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0008_alter_setup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('met', 'Met'), ('partially_met', 'Partially met'), ('unmet', 'Unmet'), ('error', 'Error')], default='unprocessed', max_length=16),
        ),
        migrations.AlterField(
            model_name='verificationrun',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('met', 'Met'), ('unmet', 'Unmet'), ('partially_met', 'Partially met'), ('error', 'Error')], max_length=16),
        ),
    ]
