# Generated by Django 5.2.6 on 2025-09-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0009_alter_requirement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='tags',
        ),
        migrations.AddField(
            model_name='setup',
            name='tags_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
