# Generated by Django 5.2.6 on 2025-09-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0010_remove_setup_tags_setup_tags_json_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
