# Generated by Django 5.2.6 on 2025-09-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0011_setup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='llm_model',
            field=models.CharField(default='model_gpt_4_1', max_length=64),
        ),
    ]
