# Generated by Django 5.2.6 on 2025-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0012_setup_llm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='agent_model',
            field=models.CharField(default='computer-use-preview', max_length=64),
        ),
    ]
