# Generated by Django 5.2.6 on 2025-09-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0013_setup_agent_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='max_reasoning_steps',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
