# Generated by Django 5.2.6 on 2025-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0014_setup_max_reasoning_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='agent_timeout_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
