# Generated by Django 5.2.6 on 2025-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0015_setup_agent_timeout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='max_retries',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
