# Generated by Django 5.2.6 on 2025-09-27 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0016_setup_max_retries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='acceptance_criteria_json',
        ),
        migrations.CreateModel(
            name='AcceptanceCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('state', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('met', 'Met'), ('unmet', 'Unmet')], default='unprocessed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='setups.requirement')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
