# Generated by Django 5.2.6 on 2025-09-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_key', models.CharField(max_length=512)),
                ('google_api_key', models.CharField(blank=True, max_length=512, null=True)),
                ('anthropic_api_key', models.CharField(blank=True, max_length=512, null=True)),
                ('num_workers', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
